// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'APIKEY',
    appId: '1:1024200502471:web:4fba6bb6ed3838fc01a2e2',
    messagingSenderId: '1024200502471',
    projectId: 'qflix-booking',
    authDomain: 'qflix-booking.firebaseapp.com',
    databaseURL: 'https://qflix-booking-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qflix-booking.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'APIKEY',
    appId: '1:1024200502471:android:0d91dab674e9290601a2e2',
    messagingSenderId: '1024200502471',
    projectId: 'qflix-booking',
    databaseURL: 'https://qflix-booking-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qflix-booking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIliwxxQ8Qqh87gldssBZjx-lfVtFbqqI',
    appId: '1:1024200502471:ios:c31ec7e7e13a910501a2e2',
    messagingSenderId: '1024200502471',
    projectId: 'qflix-booking',
    databaseURL: 'https://qflix-booking-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qflix-booking.appspot.com',
    iosBundleId: 'com.example.qflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'APIKEY',
    appId: '1:1024200502471:ios:274623ff4f66c4a001a2e2',
    messagingSenderId: '1024200502471',
    projectId: 'qflix-booking',
    databaseURL: 'https://qflix-booking-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qflix-booking.appspot.com',
    iosBundleId: 'com.example.qflix.RunnerTests',
  );
}
